### ISSUE TITLE
Pre-launch checklist

### ISSUE THREAD

**Issue by vierja** [tryolabs/luminoth#10]
- [x] Make pre-launch checklist
- [x] [Doc] Installation instructions
- [ ] [Doc] Usage instructions
- [ ] [Doc] Testing instructions
- [x] [Doc] High-level description & better name explanation
- [x] Test runner
- [x] Simple CI setup
